# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('title', models.TextField()),
                ('speaker', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(verbose_name=b'date created')),
                ('updated', models.DateTimeField(verbose_name=b'date updated')),
                ('view_count', models.IntegerField(verbose_name=b'view count')),
                ('vote_count', models.IntegerField(verbose_name=b'vote count')),
                ('fav_count', models.IntegerField(verbose_name=b'favorite count')),
            ],
        ),
    ]
