# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='created',
            field=models.DateTimeField(verbose_name=b'date created'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='updated',
            field=models.DateTimeField(verbose_name=b'date updated'),
        ),
    ]
