# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0004_auto_20170321_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='talk',
            options={'get_latest_by': '-created', 'ordering': ['-created', '-updated'], 'verbose_name': 'Talk', 'verbose_name_plural': 'Talks'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
    ]
