# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0004_auto_20170326_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='fav_count',
            field=models.PositiveIntegerField(default=0, verbose_name='favorite count'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='view count'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='vote_count',
            field=models.PositiveIntegerField(default=0, verbose_name='vote count'),
        ),
    ]
