# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_auto_20170322_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='created',
            field=models.DateTimeField(verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='fav_count',
            field=models.PositiveIntegerField(verbose_name='favorite count'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='type',
            field=models.CharField(choices=[('youtube', 'Youtube'), ('vimeo', 'Vimeo')], default='youtube', max_length=10),
        ),
        migrations.AlterField(
            model_name='talk',
            name='updated',
            field=models.DateTimeField(verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='view_count',
            field=models.PositiveIntegerField(verbose_name='view count'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='vote_count',
            field=models.PositiveIntegerField(verbose_name='vote count'),
        ),
    ]
