# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0007_remove_talk_vote_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='fav_count',
        ),
    ]
