# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0008_remove_talk_fav_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
