# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0009_auto_20170403_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='code',
            field=models.CharField(default=None, max_length=25, unique=True),
        ),
    ]
