# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0010_auto_20170403_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
