# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0011_auto_20170403_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='thumbnail',
            field=models.URLField(null=True, verbose_name='video thumbnail'),
        ),
    ]
